# Generated by Django 5.2.5 on 2025-09-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_rename_menu_menuitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='BokkingDate',
            new_name='BookingDate',
        ),
    ]
